### ISSUE TITLE
wine error

### ISSUE THREAD

**Issue by maxduke** [NyaMisty/alt-anisette-server#1]
root@17a114aad60a:/app# ./run_icloud.sh
-----------------------------------------------

If after 60 seconds you are still not seeing "Anisette Server running at http://0.0.0.0:6969/"
Please re-run the docker container as the initialize process are stucked

-----------------------------------------------
+ set -e
+ cd /app
+ sleep 10
+ wine 'C:\Program Files\Common Files\Apple\Internet Services\iCloud.exe'
+ timeout 45s wine 'Z:\ahk\AutoHotkeyU32.exe' 'Z:\app\icloud_login.ahk'

wine: Unhandled page fault on read access to 00000000 at address 01FC9328 (thread 0024), starting debugger...
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x01fc9328).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
 EIP:01fc9328 ESP:0021ed94 EBP:0021ee1c EFLAGS:00010246(  R- --  I  Z- -P- )
 EAX:010f3838 EBX:0004005c ECX:00000000 EDX:00000000
 ESI:0021efa8 EDI:00000000
Stack dump:
0x0021ed94:  00000000 68e9444e 6ed8e538 86000000
0x0021eda4:  00000000 00299fdc 00000012 0004005c
0x0021edb4:  ffff002b 0021ede8 66b0e86c 00000000
0x0021edc4:  00000000 000002e8 66b0e86c 00000001
0x0021edd4:  00000011 010f3868 010f385c 010f3860
0x0021ede4:  00296758 0021ee18 6ed89f5a 00000000
Backtrace:
=>0 0x01fc9328 EntryPoint+0x304bf() in icloud_main (0x0021ee1c)
  1 0x01d7e59d MMCopyIsCreationAllowed+0x36f6d() in icloud_main (0x0021ee3c)
  2 0x01d50947 MMCopyIsCreationAllowed+0x9317() in icloud_main (0x0021ee98)
  3 0x6ed9e03c WINPOS_SysCommandSizeMove+0xeac(hwnd=<is not available>, wParam=<is not available>) [Z:\usr\src\packages\BUILD\dlls\user32\winpos.c:3056] in user32 (0x0021eec8)
  4 0x6ed9e6f3 call_window_proc+0x63(hwnd=0004005C, msg=0x1, wp=0, lp=0x21f310, result=0021EFA8, arg=0553002D) [Z:\usr\src\packages\BUILD\dlls\user32\winproc.c:246] in user32 (0x0021ef28)
  5 0x6eda0cd6 WINPROC_call_window+0x1d6(hwnd=0004005C, msg=0x1, wParam=0, lParam=0x21f310, result=0021EFA8, unicode=0x1, mapping=262236) [Z:\usr\src\packages\BUILD\dlls\user32\winproc.c:
957] in user32 (0x0021ef78)
  6 0x6ed5f2fa call_window_proc+0x8a(hwnd=0004005C, msg=0x1, wparam=0, lparam=0x21f310, unicode=0x1, same_thread=0x1, mapping=262236) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:2220
] in user32 (0x0021efe8)
  7 0x6ed62408 send_message+0x248(info=0021F074, res_ptr=0021F070, unicode=0x1) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:3198] in user32 (0x0021f068)
  8 0x6ed62654 SendMessageW+0x54(hwnd=0004005C, msg=0x1, wparam=0, lparam=0x21f310) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:3438] in user32 (0x0021f0a8)
  9 0x6ed93770 WIN_CreateWindowEx+0x15d0(cs=<is not available>, className=<is not available>, module=<is not available>, unicode=<is not available>) [Z:\usr\src\packages\BUILD\dlls\user32
\win.c:1702] in user32 (0x0021f2f8)
  10 0x6ed8c0ec CreateWindowExW+0x77(exStyle=<is not available>, className=<is not available>, windowName=<is not available>, style=<is not available>, x=<is not available>, y=<is not ava
ilable>, width=<is not available>, height=<is not available>, parent=<is not available>, menu=<is not available>, instance=<is not available>, data=<is not available>) [Z:\usr\src\package
s\BUILD\dlls\user32\win.c:1844] in user32 (0x0021f344)
  11 0x01d45ac5 in icloud_main (+0x25ac5) (0x0021f3c4)
  12 0x01d50b1f MMCopyIsCreationAllowed+0x94ef() in icloud_main (0x0021f408)
  13 0x01d9f220 MMCopyIsCreationAllowed+0x57bf0() in icloud_main (0x0021f43c)
  14 0x01d9dc7f MMCopyIsCreationAllowed+0x5664f() in icloud_main (0x0021f508)
  15 0x01d9da16 MMCopyIsCreationAllowed+0x563e6() in icloud_main (0x0021f52c)
  16 0x01d50947 MMCopyIsCreationAllowed+0x9317() in icloud_main (0x0021f588)
  17 0x6ed9e03c WINPOS_SysCommandSizeMove+0xeac(hwnd=<is not available>, wParam=<is not available>) [Z:\usr\src\packages\BUILD\dlls\user32\winpos.c:3056] in user32 (0x0021f5b8)
  18 0x6ed9e6f3 call_window_proc+0x63(hwnd=00050052, msg=0x1, wp=0, lp=0x21fa00, result=0021F698, arg=0553001E) [Z:\usr\src\packages\BUILD\dlls\user32\winproc.c:246] in user32 (0x0021f618
)
  19 0x6eda0cd6 WINPROC_call_window+0x1d6(hwnd=00050052, msg=0x1, wParam=0, lParam=0x21fa00, result=0021F698, unicode=0x1, mapping=327762) [Z:\usr\src\packages\BUILD\dlls\user32\winproc.c
:957] in user32 (0x0021f668)
  20 0x6ed5f2fa call_window_proc+0x8a(hwnd=00050052, msg=0x1, wparam=0, lparam=0x21fa00, unicode=0x1, same_thread=0x1, mapping=327762) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:222
0] in user32 (0x0021f6d8)
  21 0x6ed62408 send_message+0x248(info=0021F764, res_ptr=0021F760, unicode=0x1) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:3198] in user32 (0x0021f758)
  22 0x6ed62654 SendMessageW+0x54(hwnd=00050052, msg=0x1, wparam=0, lparam=0x21fa00) [Z:\usr\src\packages\BUILD\dlls\user32\message.c:3438] in user32 (0x0021f798)
  23 0x6ed93770 WIN_CreateWindowEx+0x15d0(cs=<is not available>, className=<is not available>, module=<is not available>, unicode=<is not available>) [Z:\usr\src\packages\BUILD\dlls\user3
2\win.c:1702] in user32 (0x0021f9e8)
  24 0x6ed8c0ec CreateWindowExW+0x77(exStyle=<is not available>, className=<is not available>, windowName=<is not available>, style=<is not available>, x=<is not available>, y=<is not ava
ilable>, width=<is not available>, height=<is not available>, parent=<is not available>, menu=<is not available>, instance=<is not available>, data=<is not available>) [Z:\usr\src\package
s\BUILD\dlls\user32\win.c:1844] in user32 (0x0021fa3c)
  25 0x01d45ac5 in icloud_main (+0x25ac5) (0x0021fabc)
  26 0x01d50b1f MMCopyIsCreationAllowed+0x94ef() in icloud_main (0x0021fb00)
  27 0x01d9e320 MMCopyIsCreationAllowed+0x56cf0() in icloud_main (0x0021fb34)
  28 0x01d9b137 MMCopyIsCreationAllowed+0x53b07() in icloud_main (0x0021fb9c)
  29 0x01fd128b EntryPoint+0x38422() in icloud_main (0x0021fbe4)
  30 0x01fc0bcb EntryPoint+0x27d62() in icloud_main (0x0021fc3c)
  31 0x01fbe561 EntryPoint+0x256f8() in icloud_main (0x0021fce4)
  32 0x0040184c in icloud (+0x184c) (0x0021fe54)
  33 0x00401359 in icloud (+0x1359) (0x0021fe70)
  34 0x00404269 in icloud (+0x4269) (0x0021fe9c)
  35 0x00407c6f in icloud (+0x7c6f) (0x0021ff30)
  36 0x7b62dd10 WriteTapemark+0x100(device=7FFD1000, type=0x7ffd1000, count=0, immediate=0x21ffec) [Z:\usr\src\packages\BUILD\dlls\kernel32\tape.c:317] in kernel32 (0x0021ff48)
  37 0x7bc5b957 RtlWakeConditionVariable+0x57(variable=7B62DD00) [Z:\usr\src\packages\BUILD\dlls\ntdll\sync.c:757] in ntdll (0x0021ff5c)
  38 0x7bc5c010 RtlCreateUserThread(entry=00407DB2, arg=7FFD1000) [Z:\usr\src\packages\BUILD\dlls\ntdll\thread.c:261] in ntdll (0x0021ffec)
0x01fc9328 icloud_main+0x2a9328: movl   0x0(%edx),%edx
Modules:
Module  Address                 Debug info      Name (80 modules)
PE      00400000-00411000       Export          icloud
PE      00420000-008a3000       Deferred        ole32
PE      008b0000-00a01000       Deferred        combase
PE      00a10000-00a79000       Deferred        msvcp100
PE      01440000-0144f000       Deferred        yscrashdump
PE      01450000-015fd000       Deferred        corefoundation
PE      01600000-0162f000       Deferred        objc
PE      01630000-01640000       Deferred        asl
PE      01640000-01658000       Deferred        libdispatch
PE      01660000-017e9000       Deferred        winmm
PE      017f0000-019f7000       Deferred        libicuin
PE      01a00000-01b40000       Deferred        libicuuc
PE      01b40000-01b7d000       Deferred        concrt140
PE      01d20000-020e9000       Export          icloud_main
PE      020f0000-0239b000       Deferred        gdiplus
PE      023a0000-023e7000       Deferred        aoskit
PE      023f0000-0240c000       Deferred        nsi
PE      02410000-0263e000       Deferred        cfnetwork
PE      02640000-0289d000       Deferred        comdlg32
PE      028a0000-0299f000       Deferred        libxml2
PE      029a0000-02a5d000       Deferred        sqlite3
PE      02a60000-02a73000       Deferred        pthreadvc2
PE      02a80000-02d49000       Deferred        foundation
PE      02d50000-02dd0000       Deferred        netapi32
PE      02dd0000-02e0e000       Deferred        libtidy
PE      02e10000-02e33000       Deferred        userenv
PE      02e40000-03f54000       Deferred        webkit
PE      03f60000-04565000       Deferred        javascriptcore
PE      04570000-0463b000       Deferred        wtf
PE      04640000-04a47000       Deferred        coregraphics
PE      04a50000-04b37000       Deferred        coretext
PE      04b40000-04c9c000       Deferred        quartzcore
PE      04ca0000-04cc8000       Deferred        corevideo
PE      04cd0000-04cff000       Deferred        libxslt
PE      04d00000-04d02000       Deferred        usp10
PE      04d10000-04d26000       Deferred        applepushservice
PE      04d30000-04dc8000       Deferred        uxtheme
PE      04dd0000-04e56000       Deferred        secur32
PE      10000000-10007000       Deferred        appleversions
PE      4ad00000-4c6e5000       Deferred        icudt62
PE      5a4c0000-5a4d5000       Deferred        zlib1
PE      61500000-6157a000       Deferred        iphlpapi
PE      61740000-6182f000       Deferred        advapi32
PE      61940000-61b49000       Deferred        wininet
PE      62300000-6236f000       Deferred        msvcp140
PE      62ec0000-62edd000       Deferred        ncrypt
PE      62fc0000-63204000       Deferred        rpcrt4
PE      63480000-6349c000       Deferred        version
PE      637c0000-638a2000       Deferred        oleacc
PE      63bc0000-63c05000       Deferred        shcore
PE      64640000-646b1000       Deferred        msvcp120
PE      64a40000-64b60000       Deferred        shlwapi
PE      64ec0000-652ae000       Deferred        oleaut32
PE      65f40000-65f62000       Deferred        kerberos
PE      66240000-6627a000       Deferred        bcrypt
PE      663c0000-6648a000       Deferred        winspool
PE      66540000-66553000       Deferred        atlthunk
PE      66b00000-66b57000       Deferred        win32u
PE      67340000-6761b000       Deferred        msvcr120
PE      67ec0000-68cb6000       Deferred        shell32
PE      69180000-691a7000       Deferred        wsock32
PE      6a040000-6a0a3000       Deferred        msacm32
PE      6a280000-6a4eb000       Deferred        msvcrt
PE      6b080000-6b13f000       Deferred        msvcr100
PE      6bc00000-6bca3000       Deferred        sechost
PE      6c740000-6c8b7000       Deferred        cryptui
PE      6c9c0000-6cba9000       Deferred        gdi32
PE      6cc40000-6d0b7000       Deferred        comctl32
PE      6d780000-6d7ff000       Deferred        ws2_32
PE      6d880000-6d8b9000       Deferred        msv1_0
PE      6e4c0000-6e4fe000       Deferred        dnsapi
PE      6e8c0000-6eb70000       Deferred        crypt32
PE      6ed00000-6f481000       Dwarf-4         user32
PE      70240000-70254000       Deferred        vcruntime140
PE      70940000-70996000       Deferred        mpr
PE      70b40000-70e0f000       Deferred        ucrtbase
PE      71200000-7124c000       Deferred        imm32
PE      7b000000-7b307000       Deferred        kernelbase
PE      7b600000-7b920000       Dwarf-4         kernel32
PE      7bc00000-7be99000       Dwarf-4         ntdll
Threads:
process  tid      prio (all id:s are in hex)
00000020 (D) C:\Program Files\Common Files\Apple\Internet Services\iCloud.exe
        00000024    0 <==
        000000b0    0
        000000b4    0
        000000b8    0
        000000bc    0
        000004b8    0
        000004bc    0
        000004c4    0
        000004d4    0
00000038 services.exe
        0000003c    0
        00000048    0
        00000084    0
        00000088    0
        0000021c    0
        00000220    0
00000040 conhost.exe
        00000044    0
000000cc iCloudServices.exe
        000000d0    0
        000000d8    0
        000000e4    0
        000000e8    0
        00000128    0
        00000130    0
        00000134    0
        00000138    0
        0000013c    0
        00000144    0
        0000014c    0
        0000015c    0
        00000160    0
System information:
    Wine build: wine-7.3
    Platform: i386
    Version: Windows 7
    Host system: Linux
    Host version: 4.9.0-4-amd64

**Comment by NyaMisty** [comment]
Run again, for at least 10 times.
If it's synology, then not supported lol

**Comment by maxduke** [comment]
I'm running this in a VPS with kernel 4.9.0-4-amd64 and provide "restart: always"

**Comment by NyaMisty** [comment]
Well on VPS please try at least kernel 5.X. 
4.9.0 is way too old.
