### ISSUE TITLE
Feature Request: ARMx64 support

### ISSUE THREAD

**Issue by SomeAspy** [NyaMisty/alt-anisette-server#3]
ARMx64 support is incomplete for altserver due to this repo. As it seems you are the owner of both the alt-server linux repo, I will just link the other installation details.

https://github.com/NyaMisty/AltServer-Linux/releases/tag/v0.0.5

> Custom Anisette Server
> Many user have experienced -36607 error, which is a new Apple restriction based on Anisette Data.
> 
> To solve this, you can use you own anisette data service:
> 
> Pull and run [alt_anisette_server](https://hub.docker.com/r/nyamisty/alt_anisette_server) according to README.
> If you cannot build the server yourself, you can also ask other people to share the same server together
> Run export ALTSERVER_ANISETTE_SERVER="http://192.168.1.2:6969" before AltServer-Linux each time (replace the 192.168.1.2 to your server IP)
> Run AltServer-Linux

**Comment by NyaMisty** [comment]
Won't solve
Don't be too demanding. Just place it in a x86 server and expose the 6969 port

**Comment by SomeAspy** [comment]
My apologies, didn't mean to come off as demanding. thank you anyways

**Comment by NyaMisty** [comment]
Never mind lol
These Apple internal will be always full of trouble. Getting it   working in Linux x86 is already a micacle.

Also, The anisette server is fully separated from AltServer, so you can run it on your VPS, instead of using ARM64 that requires lots of tweaking.

**Comment by SomeAspy** [comment]
ah, I was trying to run it on my raspberry pi.

**Comment by JJTech0130** [comment]
Couldn't you just drop it into https://github.com/ptitSeb/box86 (or 64)? Doesn't seem like it would have any major issues... I'll try it if I have time.

**Comment by NyaMisty** [comment]
I'd suggest we maintain a community server instead...

**Comment by SomeAspy** [comment]
@NyaMisty Perhaps we should make a discord server for altserver if there isnt one already

**Comment by NyaMisty** [comment]
> @NyaMisty Perhaps we should make a discord server for altserver if there isnt one already

They had it, but now it's patreon-only

**Comment by JJTech0130** [comment]
> I'd suggest we maintain a community server instead...

Well, the problem is that it creates both a single point of failure/bottleneck, and it also requires sending your Apple ID to a third party.
