### ISSUE TITLE
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

### ISSUE THREAD

**Issue by AlyafeiAli** [NyaMisty/alt-anisette-server#5]
Hi,

I'm trying to run it on a RPi4 and I'm getting this error
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested

And this is the output of curl 127.0.0.1:6969 :
curl: (7) Failed to connect to 127.0.0.1 port 6969: Connection refused

**Comment by qeweyou** [comment]
It seems like the image doesn't run on the Raspberry Pi's architecture. There may be no way to run this on a Pi. I just tried it and it came up with the same error on my Pi 4.

EDIT: just noticed, no plans for NyaMisty to implement support. Looks like you'll have to find an x86 machine.

**Comment by AlyafeiAli** [comment]
> It seems like the image doesn't run on the Raspberry Pi's architecture. There may be no way to run this on a Pi. I just tried it and it came up with the same error on my Pi 4.
> 
> EDIT: just noticed, no plans for NyaMisty to implement support. Looks like you'll have to find an x86 machine.

Yup, sadly.
Thank you for taking the time to test it on your RPi and reply, appreciate it :)
